[phases.setup]
nixPkgs = ["python312", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install -r requirements-heavy.txt",
  "npm install -g lighthouse",
  "playwright install --with-deps chromium"
]
