[project]
name = "lighthouse-tool"
version = "0.1.0"
description = "Lighthouse performance analysis tool for Opal"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "optimizely-opal-opal-tools-sdk>=0.1.1.dev0",
]